#!/usr/bin/env node
/**
 * Emits a brand's DTCG token files, resolver and Terrazzo config.
 *
 *   node tools/tokens.mjs cru --dry
 *   node tools/tokens.mjs cru
 *
 * Output is `tokens/<brand>/`. Same inputs as `palette.mjs` and the same ramps in the same run, so
 * the token files cannot disagree with the stylesheets — see `tokens-core.mjs` for the id scheme and
 * for why formulas are deferred rather than emitted.
 *
 * The Terrazzo config is generated rather than written by hand because it carries the selector lists
 * and cascade layers, and those come from `palette-core.mjs`. Two copies of the selector list is how
 * the generated CSS and the generated tokens would quietly stop landing in the same place.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { buildRamps, carriedBlock, deriveSpec, gridFor, surfaceFor, SELECTORS } from './palette-core.mjs';
import { buildTokens } from './tokens-core.mjs';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');

const brandName = process.argv[2];
const dry = process.argv.includes('--dry');
if (!brandName) {
  console.error('usage: node tools/tokens.mjs <brand> [--dry]');
  process.exit(1);
}

const brand = JSON.parse(readFileSync(join(ROOT, `tools/brands/${brandName}.json`), 'utf8'));
const spec = deriveSpec(readFileSync(join(ROOT, 'src/styles/color/palettes/default.css'), 'utf8'));
const { ramps } = buildRamps(spec, brand);
// The same block `buildTheme` carries into the stylesheet, so the two cannot describe different metrics.
const carried = carriedBlock(
  readFileSync(join(ROOT, 'src/styles/themes/default.css'), 'utf8'),
  brand.fonts ?? {},
  brand.metrics ?? {},
);
const { files, deferred } = buildTokens({ brandName, brand, ramps, gridFor, surfaceFor, carried });

/** The config, with the selector lists read from the same place the stylesheets read them. */
function terrazzoConfig(name) {
  const sel = SELECTORS(name);
  const lit = (xs) => xs.map((s) => `'${s}'`).join(', ');
  return `// Generated by tools/tokens.mjs — do not edit by hand.
//
// Four outputs from one token set, split by id namespace so each lands in the cascade layer the
// architecture already gives it: the hue ramps, the role map, the mode-independent knobs, and the
// two per-mode blocks. \`legacyHex\` because the palette is authored as hex and the stylesheets it
// replaces are read by people; Terrazzo's default is \`rgb()\`.
import { defineConfig } from '@terrazzo/cli';
import css from '@terrazzo/plugin-css';

/** Ids are namespaced by layer; the CSS name drops that segment, and \`base\` entirely. */
const variableName = (token) => {
  const parts = token.id.split('.').slice(1);
  if (parts.at(-1) === 'base') {
    parts.pop();
  }
  return \`--cs-\${parts.join('-')}\`;
};

const wrap = (layer, selectors) => (contents) =>
  \`@layer \${layer} {\\n\${selectors.map((s) => '  ' + s).join(',\\n')} {\\n    \${contents}\\n  }\\n}\`;

const LIGHT = [${lit(sel.light)}];
const DARK = [${lit(sel.dark)}];
/** Mode-independent: every mode selector at once, matching the block \`buildTheme\` writes. */
const BOTH = [${lit(sel.light.slice(0, 3).concat(['.cs-dark', '.cs-invert']))}];

export default defineConfig({
  tokens: ['./${name}.resolver.json'],
  outDir: './build',
  plugins: [
    css({
      filename: 'palette.css',
      legacyHex: true,
      variableName,
      exclude: ['role.**', 'theme.**', 'foundation.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-color-palette', [':where(:root)', ':host']) }],
    }),
    css({
      filename: 'variants.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'theme.**', 'foundation.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-color-variant', [':where(:root)']) }],
    }),
    css({
      filename: 'foundation.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'role.**', 'theme.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-theme', BOTH) }],
    }),
    css({
      filename: 'theme.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'role.**', 'foundation.**'],
      permutations: [
        { input: { theme: 'light' }, prepare: wrap('cs-theme', LIGHT) },
        { input: { theme: 'dark' }, prepare: wrap('cs-theme', DARK) },
      ],
    }),
  ],
});
`;
}

const dir = join(ROOT, 'tokens', brandName);
const written = { ...files, 'terrazzo.config.js': terrazzoConfig(brandName) };
const paths = [];

console.log(`brand ${brandName} — ${Object.keys(ramps).length} ramps\n`);
for (const [name, body] of Object.entries(written)) {
  const text = typeof body === 'string' ? body : JSON.stringify(body, null, 2) + '\n';
  if (!dry) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, name), text);
    paths.push(join(dir, name));
  }
  console.log(`  ${dry ? 'would write' : 'wrote'}  tokens/${brandName}/${name} (${text.length} bytes)`);
}

// As in `palette.mjs`: these files are committed and `npm run verify` checks formatting, so a
// generator that emitted unformatted output would break the gate until someone ran a second command.
if (paths.length) {
  execFileSync('npx', ['prettier', '--write', '--log-level=warn', ...paths], { stdio: 'inherit' });
}

// Formulas are not a failure — but a silent change in how many there are would be, so they are
// always reported and never merely dropped.
console.log(`\n${deferred.length} deferred (formula, stays in CSS):`);
for (const d of deferred) {
  console.log(`  ${d.mode.padEnd(6)} ${d.name.padEnd(30)} ${d.value}`);
}
