import { execSync } from 'child_process';
import { mkdir, readFile } from 'fs/promises';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { dirname, join, posix, relative } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import browserSync from 'browser-sync';
import chalk from 'chalk';
import { deleteAsync } from 'del';
import esbuild from 'esbuild';
import getPort, { portNumbers } from 'get-port';
import { globby } from 'globby';
import open from 'open';
import ora from 'ora';
import copy from 'recursive-copy';
import { generateAgentSkill } from './agent-skill.js';
import { generateDesignSkill } from './design-skill.js';
import { generateLlmsTxtFile } from './llms.js';
import { formatError, getBundledDir, getDistDir, getRootDir, getUnbundledDir } from './utils.js';

// @ts-expect-error used for SSR cookies

const __dirname = dirname(fileURLToPath(import.meta.url));

const spinner = ora();
const buildContexts = {
  bundledContext: {},
  unbundledContext: {},
};

const debugPerf = process.env.DEBUG_PERFORMANCE === '1';
const isDeveloping = process.argv.includes('--develop');

if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'development';
}

/**
 * @typedef {Object} BuildOptions
 * @property {Array<string>} [watchedSrcDirectories]
 * @property {(eventName: "change" | "add" | "unlink", filePath: string) => unknown} [beforeWatchEvent]
 * @property {(eventName: "change" | "add" | "unlink", filePath: string) => unknown} [afterWatchEvent]
 * @property {(dir: string) => void} [transformTypes]
 */

/**
 * @param {BuildOptions} [options={}]
 */
export async function build(options = {}) {
  // packageData and version  need to be set within the `build()` function because this file gets imported by the app, which may not have generated its bundled directory yet, so this needs to be "lazily" evaluated.
  const packageData = JSON.parse(await readFile(join(getRootDir(), 'package.json'), 'utf-8'));
  const version = packageData.version;
  console.log(`${chalk.hex('#ef6741')('🦊 Cornerstone')} ${chalk.cyan(`v${version}\n`)}`);
  if (isDeveloping) {
    spinner.info('Development mode');
  }

  if (!options.watchedSrcDirectories) {
    options.watchedSrcDirectories = ['src'];
  }

  const transformTypes = options.transformTypes || ((_dir) => {});

  /**
   * Runs the full build.
   */
  async function buildAll() {
    const start = Date.now();

    try {
      const steps = [
        cleanup,
        generateManifest,
        generateAllComponentFile,
        generateReactWrappers,
        generateTypes,
        generateStyles,
      ];

      for (const step of steps) {
        if (debugPerf) {
          const stepStart = Date.now();
          await step();
          const elapsedTime = (Date.now() - stepStart) / 1000 + 's';
          spinner.succeed(`${step.name}: ${elapsedTime}`);
        } else {
          await step();
        }
      }

      // copy everything to unbundled before we generate bundles.
      await copy(getBundledDir(), getUnbundledDir(), { overwrite: true });

      await generateBundle();

      // Generate llms.txt (needs CEM, runs before docs)

      if (process.env.SKIP_SLOW_STEPS === 'true') {
        spinner.info('Skipping the agent files');
      } else {
        // Both skills are written to three places: the two dist builds that ship in the npm package,
        // and `.claude/skills/` at the repo root, so agents working in this repo load exactly what the
        // package publishes rather than a hand-copied snapshot. The repo-root copy is gitignored.
        //
        // These used to run from an `eleventy.after` hook, which made the agent files a side effect of
        // a docs-site build — the reason the skill was generated from rendered HTML at all. They are a
        // build output, so they are generated by the build.
        spinner.start('Generating the agent skills');
        const localSkillsDir = path.join(getRootDir(), '.claude', 'skills');
        await generateAgentSkill({
          copyTo: [path.join(getBundledDir(), 'skills/cornerstone'), path.join(localSkillsDir, 'cornerstone')],
        });
        await generateDesignSkill({
          outDirs: [
            path.join(getUnbundledDir(), 'skills/cornerstone-design'),
            path.join(getBundledDir(), 'skills/cornerstone-design'),
            path.join(localSkillsDir, 'cornerstone-design'),
          ],
        });
        spinner.succeed();

        spinner.start('Generating "llms.txt"');
        await generateLlmsTxtFile();
        spinner.succeed();
      }

      const time = (Date.now() - start) / 1000 + 's';
      spinner.succeed(`The build is complete ${chalk.gray(`(finished in ${time})`)}`);
    } catch (err) {
      spinner.fail();
      console.log(chalk.red(`\n${err}`));
    }
  }

  /** Empties the dist directory. */
  async function cleanup() {
    spinner.start('Cleaning up dist');

    // Both builds live under `dist`, so one delete clears them.
    await deleteAsync(getDistDir());
    await mkdir(getUnbundledDir(), { recursive: true });
    await mkdir(getBundledDir(), { recursive: true });

    spinner.succeed();
  }

  /**
   * Analyzes components and generates the custom elements manifest file.
   */
  function generateManifest() {
    spinner.start('Generating CEM');

    try {
      execSync('cem analyze --config "custom-elements-manifest.js"');
    } catch (error) {
      console.error(`\n\n${error.message}`);

      if (!isDeveloping) {
        process.exit(1);
      }
    }

    spinner.succeed();
    return Promise.resolve();
  }

  /**
   * Generates React wrappers for all components.
   */
  function generateReactWrappers() {
    // Used by cornerstone-app to make re-rendering not miserable with extra React file generation.
    if (process.env.SKIP_SLOW_STEPS === 'true') {
      spinner.info('Skipping React Wrapper generation.');
      return Promise.resolve();
    }

    spinner.start('Generating React wrappers');

    try {
      // need to run  make-react from this directories.
      execSync(`node ${join(__dirname, 'make-react.js')} --outdir "${getBundledDir()}"`, { stdio: 'inherit' });
    } catch (error) {
      console.error(`\n\n${error.message}`);

      if (!isDeveloping) {
        process.exit(1);
      }
    }
    spinner.succeed();

    return Promise.resolve();
  }

  function generateAllComponentFile() {
    if (process.env.SKIP_SLOW_STEPS === 'true') {
      spinner.info('Skipping "ssr/all.js" file generation.');
      return Promise.resolve();
    }

    spinner.start('Generating "ssr/all.js" file');

    try {
      // need to run make-all from this directory.
      execSync(`node ${join(__dirname, 'make-all.js')} --outdir "${getBundledDir()}"`, { stdio: 'inherit' });
    } catch (error) {
      console.error(`\n\n${error.message}`);

      if (!isDeveloping) {
        process.exit(1);
      }
    }
    spinner.succeed();

    return Promise.resolve();
  }

  /**
   * Copies theme stylesheets to the dist.
   */
  async function generateStyles() {
    spinner.start('Copying stylesheets');

    await copy(join(getRootDir(), 'src/styles'), join(getBundledDir(), 'styles'), { overwrite: true });

    spinner.succeed();

    return Promise.resolve();
  }

  /**
   * Runs TypeScript to generate types.
   */
  async function generateTypes() {
    // Used by cornerstone-app to make re-rendering not miserable with extra TS compilations.
    if (process.env.SKIP_SLOW_STEPS === 'true') {
      spinner.info('Skipping TypeScript compiler.');
      return Promise.resolve();
    }

    spinner.start('Running the TypeScript compiler');

    const cwd = process.cwd();
    try {
      if (process.env.ROOT_DIR) {
        process.chdir(process.env.ROOT_DIR);
      }
      const bundledDir = getBundledDir();
      execSync(`tsc --project ./tsconfig.prod.json --outdir "${getBundledDir()}"`, { stdio: 'inherit' });
      transformTypes(bundledDir);
      process.chdir(cwd);
    } catch (error) {
      process.chdir(cwd);
      if (!isDeveloping) {
        process.exit(1);
      }

      return Promise.reject(error.stdout);
    }

    spinner.succeed();

    return Promise.resolve();
  }

  /**
   * Runs esbuild to generate the final dist.
   */
  async function generateBundle() {
    spinner.start('Bundling with esbuild');

    const rootDir = process.env.ROOT_DIR || '.';
    // Bundled config
    const config = {
      conditions: isDeveloping ? ['development'] : [],
      format: 'esm',
      target: 'es2020',
      entryPoints: [
        //
        // IMPORTANT: Entry points MUST be mapped in package.json => exports
        //
        // Utilities
        join(rootDir, 'src/cornerstone.ts'),
        // Autoloader + utilities
        join(rootDir, 'src/cornerstone.loader.ts'),
        join(rootDir, 'src/cornerstone.ssr-loader.ts'),
        // Individual components
        ...(await globby(posix.join(rootDir, 'src/components/**/!(*.(style|test)).ts'))),
        // Translations
        ...(await globby(posix.join(rootDir, 'src/translations/**/*.ts'))),
        // Utilities
        ...(await globby(posix.join(rootDir, 'src/utilities/**/*.ts'))),
        // Events
        ...(await globby(posix.join(rootDir, 'src/events/**/*.ts'))),
        // TODO: Should `src/internal` be included?
        ...(await globby(posix.join(rootDir, 'src/ssr/**/*.ts'))),
        // React wrappers
        ...(await globby(posix.join(rootDir, 'src/react/**/*.ts'))),
      ],
      outdir: getBundledDir(),
      chunkNames: 'chunks/[name].[hash]',
      define: {
        'process.env.NODE_ENV': '"production"', // required by Floating UI
        // Lets a duplicate-registration warning name which two builds collided. See
        // src/internal/custom-element.ts.
        __CS_BUILD__: '"bundled"',
      },
      bundle: true,
      splitting: true,
      minify: false,
      banner: {
        js: `/*! Cornerstone Components ${version} - MIT licensed. See LICENSE.md and NOTICE. */`,
      },
    };

    const unbundledConfig = {
      ...config,
      define: { ...config.define, __CS_BUILD__: '"unbundled"' },
      splitting: true,
      treeShaking: true,
      // Don't inline libraries like Lit etc.
      packages: 'external',
      outdir: getUnbundledDir(),
    };

    /**
     * A single self-contained file with all 70 components in it: no chunks, no dynamic import, no URL built
     * at runtime. That makes it the one artifact a fingerprinting asset pipeline can serve — Propshaft,
     * Sprockets, Django's ManifestStaticFilesStorage, Laravel's Vite integration all rename every file, and
     * the split builds die on their own relative `./chunks/` specifiers before any library code runs.
     *
     * Entry is the generated `src/ssr/all.ts`, whose 70 re-exports register every component by side effect.
     * Minified because it is large by construction and there is no tree shaking to be had from an entry
     * whose whole purpose is to include everything.
     */
    const allInOneConfig = {
      ...config,
      entryPoints: [posix.join(rootDir, 'src/ssr/all.ts')],
      outfile: posix.join(getBundledDir(), 'cornerstone.all.js'),
      outdir: undefined,
      splitting: false,
      minify: true,
      chunkNames: undefined,
    };

    try {
      if (isDeveloping) {
        buildContexts.bundledContext = await esbuild.context(config);
        buildContexts.unbundledContext = await esbuild.context(unbundledConfig);

        await buildContexts.bundledContext.rebuild();
        await buildContexts.unbundledContext.rebuild();
      } else {
        // One-time build for production
        await esbuild.build(config);
        await esbuild.build(unbundledConfig);
        await esbuild.build(allInOneConfig);
      }
    } catch (error) {
      spinner.fail();
      console.log(chalk.red(`\n${error}`));
      if (!isDeveloping) {
        process.exit(1);
      }
    }

    spinner.succeed();
  }

  /**
   * Incrementally rebuilds the source files. Must be called only after `generateBundle()` has been called.
   */
  async function regenerateBundle() {
    try {
      spinner.start('Re-bundling with esbuild');
      await buildContexts.bundledContext.rebuild();
      await buildContexts.unbundledContext.rebuild();
    } catch (error) {
      spinner.fail();
      console.log(chalk.red(`\n${error}`));

      if (!isDeveloping) {
        process.exit(1);
      }
    }

    spinner.succeed();
  }

  // Initial build
  await buildAll();

  if (!isDeveloping) {
    console.log(); // just a newline for readability
  }

  // Launch the dev server
  if (isDeveloping) {
    spinner.start('Launching the dev server');

    const bs = browserSync.create();
    const port = await getPort({ port: portNumbers(4000, 4999) });
    const url = `http://localhost:${port}/`;
    const reload = () => {
      spinner.start('Reloading browser');
      bs.reload();
      spinner.succeed();
    };

    await initLitSsr();

    // Launch browser sync
    bs.init(
      {
        open: false,
        startPath: '/',
        port,
        logLevel: 'silent',
        logPrefix: '[cornerstone]',
        logFileChanges: true,
        notify: false,
        single: false,
        ghostMode: false,
        server: {
          baseDir: getDistDir(),
          routes: {
            '/dist/': './dist/bundled/',
          },
        },
      },
      () => {
        spinner.succeed();
        console.log(`\nThe dev server is running at ${chalk.cyan(url)}\n`);
        open(url);
      },
    );

    const watchEvents = ['change', 'unlink', 'add'];
    // Rebuild and reload when source files change
    options.watchedSrcDirectories.forEach((dir) => {
      const watcher = bs.watch(join(dir, '**', '!(*.test).*'), {
        ignoreInitial: true,
      });

      watchEvents.forEach((evt) => {
        watcher.on(evt, handleWatchEvent(evt));
      });
      function handleWatchEvent(evt) {
        return async (filename) => {
          const changedFile = relative(getRootDir(), filename);

          if (evt === 'change') {
            spinner.info(`File modified ${chalk.gray(`(${changedFile})`)}`);
          } else if (evt === 'unlink') {
            spinner.info(`File deleted ${chalk.gray(`(${changedFile})`)}`);
          } else if (evt === 'add') {
            spinner.info(`File added ${chalk.gray(`(${changedFile})`)}`);
          }

          try {
            const isTestFile = filename.includes('.test.ts');
            const isCssStylesheet = filename.includes('.css');
            const isComponent =
              filename.includes('components/') && filename.includes('.ts') && !isCssStylesheet && !isTestFile;

            // Re-bundle when relevant files change
            if (isTestFile) {
              return;
            }

            if (typeof options.beforeWatchEvent === 'function') {
              await options.beforeWatchEvent(evt, filename);
            }

            // Copy stylesheets when CSS files change
            if (isCssStylesheet) {
              await generateStyles();
            }

            // Regenerate metadata when components change
            if (isComponent) {
              await generateManifest();
            }

            // copy everything to unbundled before we generate bundles.
            // this may cause watcher events to break. if things are broken with file watching, comment this out.
            await copy(getBundledDir(), getUnbundledDir(), { overwrite: true });
            await regenerateBundle();
            await initLitSsr(); // Reload components SSR definitions.

            // This needs to be outside of "isComponent" check because SSR needs to run on CSS files too.

            if (typeof options.afterWatchEvent === 'function') {
              await options.afterWatchEvent(evt, filename);
            }

            reload();
          } catch (err) {
            console.error(chalk.red(formatError(err)));

            if (!isDeveloping) {
              process.exit(1);
            }
          }
        };
      }
    });
  }

  //
  // Cleanup everything when the process terminates
  //
  function terminate() {
    // dispose of contexts.
    Object.values(buildContexts).forEach((context) => context?.dispose?.());

    if (spinner) {
      spinner.stop();
    }

    process.exit();
  }

  process.on('SIGINT', terminate);
  process.on('SIGTERM', terminate);
}

// https://exploringjs.com/nodejs-shell-scripting/ch_nodejs-path.html#detecting-if-module-is-main
// Detects if this was called via node scripts/build.js
function isRunAsMain() {
  if (import.meta.url.startsWith('file:')) {
    // (A)
    const modulePath = fileURLToPath(import.meta.url);
    if (process.argv[1] === modulePath) {
      // (B)
      return true;
    }
  }

  return false;
}

async function loadComponents() {
  const baseDir = path.join(getUnbundledDir(), 'components');
  await Promise.allSettled(
    fs.readdirSync(baseDir, { recursive: false, encoding: 'utf8' }).map((dir) => {
      const component = path.basename(dir);

      const modulePath = path.join(baseDir, component, component + '.js');

      return import(modulePath + `?cachebust=${new Date().getTime()}`);
    }),
  );
}

export async function initLitSsr() {
  await loadComponents();
}

if (isRunAsMain()) {
  await build();
}
