// Generated by tools/tokens.mjs — do not edit by hand.
//
// Four outputs from one token set, split by id namespace so each lands in the cascade layer the
// architecture already gives it: the hue ramps, the role map, the mode-independent knobs, and the
// two per-mode blocks. `legacyHex` because the palette is authored as hex and the stylesheets it
// replaces are read by people; Terrazzo's default is `rgb()`.
import { defineConfig } from '@terrazzo/cli';
import css from '@terrazzo/plugin-css';

/** Ids are namespaced by layer; the CSS name drops that segment, and `base` entirely. */
const variableName = (token) => {
  const parts = token.id.split('.').slice(1);
  if (parts.at(-1) === 'base') {
    parts.pop();
  }
  return `--cs-${parts.join('-')}`;
};

const wrap = (layer, selectors) => (contents) =>
  `@layer ${layer} {\n${selectors.map((s) => '  ' + s).join(',\n')} {\n    ${contents}\n  }\n}`;

const LIGHT = [
  ':where(:root)',
  '.cs-theme-cru',
  '.cs-light',
  '.cs-dark .cs-invert',
  '.cs-light .cs-theme-cru',
  '.cs-dark .cs-theme-cru.cs-invert',
  '.cs-dark .cs-theme-cru .cs-invert',
];
const DARK = [
  '.cs-dark',
  '.cs-light .cs-invert',
  '.cs-dark .cs-theme-cru',
  '.cs-light .cs-theme-cru.cs-invert',
  '.cs-light .cs-theme-cru .cs-invert',
];
/** Mode-independent: every mode selector at once, matching the block `buildTheme` writes. */
const BOTH = [':where(:root)', '.cs-theme-cru', '.cs-light', '.cs-dark', '.cs-invert'];

export default defineConfig({
  tokens: ['./cru.resolver.json'],
  outDir: './build',
  plugins: [
    css({
      filename: 'palette.css',
      legacyHex: true,
      variableName,
      exclude: ['role.**', 'theme.**', 'foundation.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-color-palette', [':where(:root)', ':host']) }],
    }),
    css({
      filename: 'variants.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'theme.**', 'foundation.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-color-variant', [':where(:root)']) }],
    }),
    css({
      filename: 'foundation.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'role.**', 'theme.**'],
      permutations: [{ input: { theme: 'light' }, prepare: wrap('cs-theme', BOTH) }],
    }),
    css({
      filename: 'theme.css',
      legacyHex: true,
      variableName,
      exclude: ['palette.**', 'role.**', 'foundation.**'],
      permutations: [
        { input: { theme: 'light' }, prepare: wrap('cs-theme', LIGHT) },
        { input: { theme: 'dark' }, prepare: wrap('cs-theme', DARK) },
      ],
    }),
  ],
});
